version: "3"

services:
  nginx:
    # mapping port 5000 to 80 of nginx
    ports:
      - "80:80"
  node-app:
    build:
      context: .
      # Injects the NODE_ENV for Dockerfile to use
      # and be able to make decision to use production
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: npm start
    # command: node index.js