# Docker-compose file for shared services between development and production
version: '3'
services:
  node-app:
    build: .
    # port to listen to
    ports:
      -  "5000:5000"

      # Environment variable
    environment:
      - PORT=5000
    depends_on:
      - mongo
  
  # Mongo services
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ralph
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      # Named volume. Database volumes are needed to avoid lost of data if container is down
      # NOTE: Named volumes must be declared before any services can use it
      - mongo-db:/data/db

      
  # Defined here, cos we will need it in production and in development.
  redis:
    image: redis



# Declaration of named volumes
volumes:
  mongo-db: